<?php
/**
 * Created by PhpStorm.
 * User: Knyazyan
 * Date: 9/29/15
 * Time: 3:21 PM
 */

namespace TTMainBundle\Entity\Repository;

use TTMainBundle\Entity\Courts;
use Doctrine\ORM\EntityRepository;

/**
 * CourtsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourtsRepository extends EntityRepository
{
    public function getCompanies()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(c) AS courtCount, c.companyName  FROM TTMainBundle:Courts c GROUP BY c.companyName');
        $companies = $query->getResult();

        return $companies;
    }

    public function updateCourts($id, $companySubName, $surfaceType, $coverType, $countryIsoCode, $state, $city, $street)
    {
        $em = $this->getEntityManager();
        $co = $em->getRepository('TTMainBundle:Courts')->findOneById($id);

        if (!$co) {
            return false;
        }

        $co->setCompanySubName($companySubName);
        $co->setSurfaceType($surfaceType);
        $co->setCoverType($coverType);
        $co->setCountryIsoCode($countryIsoCode);
        $co->setState($state);
        $co->setCity($city);
        $co->setStreet($street);

        $em->persist($co);
        $em->flush();

        return true;
    }
}