<?php
/**
 * Created by PhpStorm.
 * User: Knyazyan
 * Date: 9/29/15
 * Time: 3:21 PM
 */

namespace TTMainBundle\Entity\Repository;

use TTMainBundle\Entity\SubCompanies;
use Doctrine\ORM\EntityRepository;

/**
 * SubCompaniesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCompaniesRepository extends EntityRepository
{

}