# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        TTMainBundle\Entity\ClientUsers: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_USER:        [ROLE_SHOPPER, ROLE_PLATFORM]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [client_users, in_memory]

        in_memory:
            memory:
                users:
                    tt_admin: { password: Pass1234, roles: [ 'ROLE_ADMIN' ] }

        client_users:
            entity: { class: TTMainBundle:ClientUsers }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        admin:
            pattern:  ^/backend/private
            anonymous: ~
            provider: in_memory
            http_basic:
              realm: "Private content!"
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            provider: client_users
            form_login:
                check_path: login_check
                login_path: login_route
                default_target_path: client_backend
            logout:
                path:   logout_route
                target: /
            anonymous: ~

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/clientBackend, role: ROLE_USER }
#        - { path: ^/payment/callback, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/payment, role: IS_AUTHENTICATED_FULLY, requires_channel: https }
#        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/private, roles: ROLE_ADMIN }